### PR TITLE
Flag: Update api, fix errors and formatting

### LINKED ISSUE #3307: Flag Upgrades
# Summary
This is a newer component and is setup well following the composition structure style. Only changes needed are updating the additional class prop names. Please follow the deprecation strategy for updating prop names.

update: use deprecation strategy

## React
- Change `additionalMediaClasses` to `mediaAdditionalClasses`
- Change `additionalBodyClasses` to `bodyAdditionalClasses`
- `children` is missing from propTypes.
- Fix eslint errors

## Angular
- Change `additionalMediaClasses` to `mediaAdditionalClasses`
- Change `additionalBodyClasses` to `bodyAdditionalClasses`

# both
- Update Upgrade Guide for both frameworks.

### PR DESCRIPTION
**Pull request by RVMendoza**
## What does this PR do?
- Change additionalMediaClasses to mediaAdditionalClasses
Change additionalBodyClasses to bodyAdditionalClasses
children is missing from propTypes.
- Update eslint rule that's conflicting with prettier
  - https://github.com/prettier/eslint-config-prettier/issues/148

### Associated Issue
Fixes #3307 

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Documentation
 - [x] Update Spark Docs

### Code
 - [x] Build Component in Angular
 - [x] Build Component in React
 - [x] Unit Testing in Angular with `npm run test` in `angular/` (100% coverage, 100% passing)
 - [x] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [x] Google Chrome
  - [x] Google Chrome (Mobile)
  - [x] Mozilla Firefox
  - [x] Mozilla Firefox (Mobile)
  - [x] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [x] Microsoft Edge
  - [x] Apple Safari
  - [x] Apple Safari (Mobile)

### CODE REVIEW

File: angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts [hunk 1]
```diff
@@ -32,14 +28,32 @@ export class SprkFlagComponent {
...
   /**
    * Expects a space separated string
    * of classes to be added to the
    * container of the body-slot.
    */
   @Input()
+  bodyAdditionalClasses: string;
+
+  /**
+   * Deprecated: Expects a space separated string
```
Comment (afebbraro) [inline angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts:42]: In the deprecated message, lets add what they should be using instead.

File: angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts [hunk 2]
```diff
@@ -32,14 +28,32 @@ export class SprkFlagComponent {
...
+   * of classes to be added to the
+   * container of the media-slot.
+   * To be removed next release.
+   */
+  @Input()
+  additionalMediaClasses: string;
+
+  /**
+   * Deprecated: Expects a space separated string
```
Comment (afebbraro) [inline angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts:51]: In the deprecated message, lets add what they should be using instead.

File: angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts (hunk 1 above)
Comment (RVMendoza) [reply angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts]: Fixed! 
image

File: angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts (hunk 2 above)
Comment (RVMendoza) [reply angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts]: fixed! 
image

File: angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.spec.ts [hunk 3]
```diff
@@ -24,22 +24,36 @@ describe('SprkFlagComponent', () => {
...
+  });
+
+  it('should add the correct classes if bodyAdditionalClasses are supplied', () => {
+    component.bodyAdditionalClasses = 'sprk-u-pam sprk-u-man';
+    expect(component.getBodyClasses()).toEqual(
+      'sprk-o-Flag__body sprk-u-pam sprk-u-man',
     );
   });
 
+  // TO DEPRECATE NEXT RELEASE
```
Comment (guern1kn) [inline angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.spec.ts:44]: I think we should use TODO in these two spots. That's what we use in other places and it will be easier to search for if we're consistent.

File: angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts [hunk 4]
```diff
@@ -132,8 +149,15 @@ export class SprkFlagComponent {
   getMediaClasses(): string {
     const mediaClassArray: string[] = ['sprk-o-Flag__figure'];
 
+    if (this.mediaAdditionalClasses) {
+      this.mediaAdditionalClasses.split(' ').forEach((className) => {
+        mediaClassArray.push(className);
+      });
+    }
+
+    // TO DEPRECATE ON NEXT RELEASE
```
Comment (guern1kn) [inline angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts:158]: TODO

File: angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts [hunk 5]
```diff
@@ -146,8 +170,15 @@ export class SprkFlagComponent {
   getBodyClasses(): string {
     const bodyClassArray: string[] = ['sprk-o-Flag__body'];
 
+    if (this.bodyAdditionalClasses) {
+      this.bodyAdditionalClasses.split(' ').forEach((className) => {
+        bodyClassArray.push(className);
+      });
+    }
+
+    // TO DEPRECATE ON NEXT RELEASE
```
Comment (guern1kn) [inline angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts:179]: TODO

File: react/src/components/flag/SprkFlag.js [hunk 6]
```diff
@@ -4,8 +4,10 @@ import classnames from 'classnames';
```
Comment (guern1kn) [inline react/src/components/flag/SprkFlag.js:4]: Let's add the TODOs somewhere in this file to deprecate as well

File: react/src/components/flag/SprkFlag.test.js [hunk 7]
```diff
@@ -54,32 +54,68 @@ describe('SprkFlag:', () => {
...
+            src="https://spark-assets.netlify.app/spark-logo-mark.svg"
+          />
+        }
+        additionalClasses={testClass}
+      />,
+    );
+    expect(wrapper.find('.sprk-o-Flag__body').hasClass(testClass)).toBe(true);
+  });
+
+  // TO DEPRECATE ON NEXT RELEASE
```
Comment (guern1kn) [inline react/src/components/flag/SprkFlag.test.js:87]: TODO

File: react/src/components/flag/SprkFlag.test.js [hunk 8]
```diff
@@ -54,32 +54,68 @@ describe('SprkFlag:', () => {
...
+            src="https://spark-assets.netlify.app/spark-logo-mark.svg"
+          />
+        }
+        additionalClasses={testClass}
+      />,
+    );
+    expect(wrapper.find('.sprk-o-Flag__figure').hasClass(testClass)).toBe(true);
+  });
+
+  // TO DEPRECATE ON NEXT RELEASE
```
Comment (guern1kn) [inline react/src/components/flag/SprkFlag.test.js:105]: TODO

File: angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.spec.ts (hunk 3 above)
Comment (RVMendoza) [reply angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.spec.ts]: image
Done!

File: angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts (hunk 4 above)
Comment (RVMendoza) [reply angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts]: Done!

File: angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts (hunk 5 above)
Comment (RVMendoza) [reply angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts]: Done!

File: react/src/components/flag/SprkFlag.js (hunk 6 above)
Comment (RVMendoza) [reply react/src/components/flag/SprkFlag.js:4]: image
Done!

File: react/src/components/flag/SprkFlag.test.js (hunk 7 above)
Comment (RVMendoza) [reply react/src/components/flag/SprkFlag.test.js]: Done!

File: react/src/components/flag/SprkFlag.test.js (hunk 8 above)
Comment (RVMendoza) [reply react/src/components/flag/SprkFlag.test.js]: Done!
