### PR TITLE
IE 11 - ordered lists not numbering - list refactor

### LINKED ISSUE #1404: [Bug/Research] Spark Angular Ordered Lists not being numbered correctly in IE11
## Describe The Bug
Take a look at the screenshot. In Angular in IE11, spark ordered lists are not being numbered correctly. 
Screen Shot 2019-05-13 at 3 47 29 PM

## To Reproduce
1. Go to lists in spark angular in IE11.
2. Look at numbering.

## Expected Behavior
Should be numbered appropriately...1,2,3 ETC. 

## Screenshots
Screen Shot 2019-05-13 at 3 47 29 PM

## Desktop (please complete the following information):
 - OS: [e.g. iOS] all
 - Browser [e.g. chrome, safari] IE11
 - Version [e.g. 22] 11

### PR DESCRIPTION
**Pull request by RVMendoza**
## What does this PR do?
A clear and concise description of what this PR does.

### Associated Issue 
Fixes #1404 

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR
then please remove it.

### Code
 - [x] Build Component in Spark Angular
 - [x] Unit Testing in Spark Angular with `gulp test-angular` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [x] Google Chrome
  - [x] Google Chrome (Mobile)
  - [x] Mozilla Firefox
  - [x] Mozilla Firefox (Mobile)
  - [x] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [x] Microsoft Edge
  - [x] Apple Safari
  - [x] Apple Safari (Mobile)

### CODE REVIEW

File: src/angular/projects/spark-angular/src/lib/components/sprk-unordered-list/sprk-unordered-list.component.ts [hunk 1]
```diff
@@ -1,10 +1,18 @@
...
   template: `
     <ul [ngClass]="getClasses()" [attr.data-id]="idString">
-      <ng-content></ng-content>
+      <li
+        *ngFor="let item of items; "
+        [attr.data-analytics]="item.analyticsString"
+        [attr.data-id]="item.idString"
+        [ngClass]="item.additionalClasses"
+      >
+        <ng-container [ngTemplateOutlet]="item.content"></ng-container>
```
Comment (afebbraro) [inline src/angular/projects/spark-angular/src/lib/components/sprk-unordered-list/sprk-unordered-list.component.ts]: Nice, this is a good use of ng-container!
