### PR TITLE
change htmlFor to id on input

### LINKED ISSUE #2195: [Bug] TextareaCheck sets htmlFor={id} when it should set id={id} ... Spark inputs dont have Id attrbute
## Describe The Bug
Currently spark ID attributes don't have ID. Mistake in prop setting causes a for attribute to get rendered on an input / textarea instead of the id

**Notes:**
- came from a talk with Patrick
- TextareCheck has been renamed to spark input element
- Currently broke today.

**AC:**
- All Spark inputs will have and ID attribute in React
- TextareaCheck will set id={id}

### PR DESCRIPTION
**Pull request by RVMendoza**
## What does this PR do?
Change htmlFor attribute on input to id

### Associated Issue
Fixes #2195

### Documentation
 - [x] Update Spark Docs

### Code
 - [x] Build Component in React
 - [x] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [x] Google Chrome
  - [x] Google Chrome (Mobile)
  - [x] Mozilla Firefox
  - [x] Mozilla Firefox (Mobile)
  - [x] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [x] Microsoft Edge
  - [x] Apple Safari
  - [x] Apple Safari (Mobile)

### CODE REVIEW

File: react/src/base/inputs/components/SprkInputElement/SprkInputElement.js [hunk 1]
```diff
@@ -67,7 +67,7 @@ class SprkInputElement extends Component {
           'sprk-b-InputContainer__input--has-icon-right': iconRight,
         })}
         type={type}
-        htmlFor={id}
+        id={id}
```
Comment (guern1kn) [inline react/src/base/inputs/components/SprkInputElement/SprkInputElement.js]: Instead of replacing the `htmlFor` can we add the `id={id}` while maintaining support for `htmlFor` in case someone is using it? It would mean both would render with the `id` but I think removing it and changing the API qualifies as a breaking change.

Comment (RVMendoza) [reply react/src/base/inputs/components/SprkInputElement/SprkInputElement.js]: htmlFor is only for "for" and should be put on labels. It wasn't working or affecting anything, and this is correcting it because inputs should have IDs, not `for`

```
<label htmlFor="username">Username</label>
<input name="username" id="username" type="text"/>
```

Comment (guern1kn) [reply react/src/base/inputs/components/SprkInputElement/SprkInputElement.js]: Ok. Looks like the propType description for id needs to be updated. References htmlFor.

Comment (RVMendoza) [reply react/src/base/inputs/components/SprkInputElement/SprkInputElement.js]: I'm seeing the user isn't able to set id on this in general. Adding that functionality now

Comment (RVMendoza) [reply react/src/base/inputs/components/SprkInputElement/SprkInputElement.js]: changed!

File: react/src/base/inputs/SprkErrorContainer/SprkErrorContainer.js [hunk 2]
```diff
@@ -33,7 +33,7 @@ SprkErrorContainer.propTypes = {
    */
   analyticsString: PropTypes.string,
   /**
-   * Configured by parent and assigned to the `htmlFor` attribute.
+   * Assigned to the `id` attribute Automatically configured if not provided.
```
Comment (guern1kn) [inline react/src/base/inputs/SprkErrorContainer/SprkErrorContainer.js]: Need a period in here after attribute
