### PR TITLE
Tooltip Width bug

### LINKED ISSUE #3806: Tooltip rendering incorrectly on narrow viewports
The Tooltip component is sometimes rendering incorrectly, causing the page to zoom unpredictably and requiring users to scroll to see all content.

tooltip

## To Reproduce
1. Go to https://nifty-archimedes-e20fac.netlify.app/
2. Open Chrome Dev Tools and turn on Device Emulation (the icon next to the Elements tab)
3. Reload the page
4. Observe that the page can be scrolled horizontally
5. Open the Tooltip - the tooltip renders horizontally off the page
6. Opening and closing the tooltip repeatedly causes it to repeatedly recalculate its width and alter the viewport width 

## Expected Behavior
The Tooltip should be able to render in a viewport that is 320px or wider without requiring a horizontal scrollbar.

Reported in Angular but happening in all frameworks.

### PR DESCRIPTION
**Pull request by guern1kn**
## What does this PR do?
Updates the values that are used to calculate the width of the tooltip to be based of the `clientWidth` & `clientHeight`

### Associated Issue
Fixes #3806 

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Code
 - [x] Build Component in HTML
 - [x] Build Component in Angular
 - [x] Build Component in React
 - [x] Unit Testing in HTML with `npm run test` in `html/` (100% coverage, 100% passing)
 - [x] Unit Testing in Angular with `npm run test` in `angular/` (100% coverage, 100% passing)
 - [x] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [x] Google Chrome
  - [x] Google Chrome (Mobile) - Pixel 5
  - [x] Mozilla Firefox
  - [x] Mozilla Firefox (Mobile) - Pixel 5
  - [x] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [x] Microsoft Edge
  - [x] Microsoft Edge (Mobile) - Pixel 5
  - [x] Opera (Mobile) - Pixel 5
  - [x] Apple Safari
  - [x] Apple Safari (Mobile) -  iPhone 12 Pro
  
### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

### CODE REVIEW

**Review by afebbraro — CHANGES_REQUESTED** [review]
Could you add in that window check I pasted on the issue?

**Comment by bobwise** [comment]
I am still seeing the bug in macOS Safari and iOS Safari using this test app (without text zoom) https://jolly-raman-0e3a89.netlify.app/

File: html/components/tooltip.js [hunk 1]
```diff
@@ -12,17 +12,18 @@ import toggleAriaExpanded from '../utilities/toggleAriaExpanded';
...
-    .replace('sprk-c-Tooltip--bottom-right', '')
-    .replace('sprk-c-Tooltip--bottom-left', '')
-    .replace('sprk-c-Tooltip--top-right', '')
-    .replace('sprk-c-Tooltip--top-left', '');
+  tooltip.classList.remove(
+    'sprk-c-Tooltip--bottom-right',
+    'sprk-c-Tooltip--bottom-left',
+    'sprk-c-Tooltip--top-right',
+    'sprk-c-Tooltip--top-left',
+  );
```
Comment (bobwise) [inline html/components/tooltip.js:20]: Thank you for fixing this!

**Review by bobwise — APPROVED** [review]

**Review by afebbraro — APPROVED** [review]
